In [8]:
import numpy as np
np.ones(4).reshape(4,1)+np.ones(4).reshape(4,1)

array([[2.],
       [2.],
       [2.],
       [2.]])

In [17]:
a=np.array([-0.33677979,  0.3321235,  -0.05716219,  0.48765791])
b=np.array([[-0.59164337],[ 0.08883106],[-0.51660265],[ 0.48595044]]).reshape(1,4)
a,b

(array([-0.33677979,  0.3321235 , -0.05716219,  0.48765791]),
 array([[-0.59164337,  0.08883106, -0.51660265,  0.48595044]]))

In [22]:
(a+b).ravel().shape

(4,)

In [23]:
(a+b).shape

(1, 4)