In [2]:
from yieldMaturitySelector import yieldMatSelector
import numpy as np
import pandas as pd

In [3]:
nominal_yields = pd.read_excel('nominal_yields.xlsx')

In [4]:
nominal_yields

Date         BETA0     BETA1       BETA2       BETA3  SVEN1F01  \
0    2005-01-03  6.189826e-06  2.277828    2.659254   16.057365    3.4022   
1    2005-01-04  2.549831e-09  2.259019    3.046883   16.223499    3.5231   
2    2005-01-05  4.330379e-05  2.259806    3.089485   16.079062    3.5391   
3    2005-01-06  1.834049e-12  2.257302    2.977634   16.110743    3.5090   
4    2005-01-07  1.780984e-12  2.304075    2.956248   16.007722    3.5372   
...         ...           ...       ...         ...         ...       ...   
4603 2022-08-25  4.087565e+00 -1.184757  469.371899 -470.490088    3.4961   
4604 2022-08-26  3.976945e+00 -1.024568  449.495350 -450.365532    3.5270   
4605 2022-08-29  3.991236e+00 -0.988008  461.435958 -462.223358    3.5611   
4606 2022-08-30  3.904771e+00 -0.882223  384.156386 -384.735830    3.5953   
4607 2022-08-31  3.969190e+00 -0.836601  340.042205 -340.922128    3.5598   

      SVEN1F04  SVEN1F09  SVENF01  SVENF02  ...  SVENY23  SVENY24  SVENY25  \
0       4.3567    5.7028   3.1680   3.5462  ...   5.0962   5.0874   5.0729   
1       4.4071    5.7558   3.2872   3.6552  ...   5.1584   5.1495   5.1350   
2       4.3983    5.7099   3.3009   3.6710  ...   5.1227   5.1131   5.0981   
3       4.4031    5.7234   3.2678   3.6475  ...   5.1278   5.1183   5.1032   
4       4.4163    5.6898   3.2920   3.6785  ...   5.1104   5.1006   5.0854   
...        ...       ...      ...      ...  ...      ...      ...      ...   
4603    2.8997    3.1778   3.4722   3.4026  ...   3.4736   3.4978   3.5204   
4604    2.9480    3.1451   3.4989   3.4386  ...   3.4318   3.4532   3.4732   
4605    3.0442    3.2161   3.5248   3.4832  ...   3.4802   3.5002   3.5188   
4606    3.0218    3.2020   3.5686   3.5038  ...   3.4509   3.4688   3.4855   
4607    3.0869    3.2537   3.5368   3.4782  ...   3.4932   3.5118   3.5291   

      SVENY26  SVENY27  SVENY28  SVENY29  SVENY30      TAU1       TAU2  
0      5.0535   5.0295   5.0014   4.9697   4.9348  1.436363  13.431858  
1      5.1155   5.0913   5.0631   5.0312   4.9960  1.393715  13.471621  
2      5.0780   5.0535   5.0249   4.9928   4.9574  1.412061  13.445450  
3      5.0831   5.0586   5.0299   4.9977   4.9623  1.423321  13.430211  
4      5.0651   5.0405   5.0118   4.9796   4.9442  1.476347  13.455895  
...       ...      ...      ...      ...      ...       ...        ...  
4603   3.5415   3.5612   3.5796   3.5969   3.6130  2.669846   2.687069  
4604   3.4918   3.5093   3.5256   3.5409   3.5553  2.690449   2.707254  
4605   3.5363   3.5527   3.5680   3.5823   3.5957  2.713702   2.728982  
4606   3.5012   3.5157   3.5294   3.5422   3.5541  2.598424   2.615921  
4607   3.5454   3.5606   3.5748   3.5882   3.6007  2.744672   2.763328  

[4608 rows x 100 columns]

In [5]:
nominal_yields[['Date', 'SVENY02', 'SVENY03', 'SVENY05', 'SVENY07',
                                       'SVENY10']].apply(lambda x: x / 100 if x.name not in 'Date' else x).loc[0:20]

Date   SVENY02   SVENY03   SVENY05   SVENY07   SVENY10
0  2005-01-03  0.030871  0.032890  0.036338  0.039640  0.044030
1  2005-01-04  0.031830  0.033839  0.037137  0.040332  0.044659
2  2005-01-05  0.031947  0.033959  0.037198  0.040308  0.044522
3  2005-01-06  0.031679  0.033726  0.037060  0.040240  0.044513
4  2005-01-07  0.031964  0.034021  0.037313  0.040402  0.044544
5  2005-01-10  0.032147  0.034198  0.037419  0.040417  0.044445
6  2005-01-11  0.032129  0.034115  0.037216  0.040117  0.044053
7  2005-01-12  0.032003  0.033980  0.037101  0.040019  0.043950
8  2005-01-13  0.031768  0.033645  0.036651  0.039532  0.043441
9  2005-01-14  0.032257  0.034126  0.037064  0.039854  0.043654
10 2005-01-17       NaN       NaN       NaN       NaN       NaN
11 2005-01-18  0.032410  0.034288  0.037131  0.039775  0.043389
12 2005-01-19  0.032425  0.034348  0.037169  0.039758  0.043300
13 2005-01-20  0.031998  0.033828  0.036695  0.039433  0.043157
14 2005-01-21  0.031519  0.033375  0.036369  0.039202  0.043005
15 2005-01-24  0.031916  0.033616  0.036306  0.038996  0.042716
16 2005-01-25  0.032232  0.034058  0.036914  0.039677  0.043445
17 2005-01-26  0.032554  0.034315  0.037036  0.039716  0.043416
18 2005-01-27  0.032700  0.034544  0.037335  0.039970  0.043569
19 2005-01-28  0.032324  0.034064  0.036740  0.039315  0.042870
20 2005-01-31  0.032573  0.034251  0.036788  0.039259  0.042716

In [6]:
yieldselector = yieldMatSelector()

In [7]:
nominal_yields_2_10y_eom = yieldselector.adjustYieldSerie(df=nominal_yields, yieldtype='nominal', FD=False)

In [8]:
nominal_yields_2_10y_eom

Date   SVENY02   SVENY03   SVENY05   SVENY07   SVENY10
0   2005-01-31  0.032573  0.034251  0.036788  0.039259  0.042716
1   2005-02-28  0.035845  0.037567  0.039757  0.041797  0.044732
2   2005-03-31  0.037855  0.039514  0.041429  0.043275  0.046031
3   2005-04-29  0.036232  0.037250  0.038608  0.040260  0.042946
4   2005-05-31  0.035692  0.036303  0.037129  0.038468  0.040887
..         ...       ...       ...       ...       ...       ...
207 2022-04-29  0.027184  0.028933  0.029325  0.029250  0.029477
208 2022-05-31  0.025223  0.027241  0.028340  0.028575  0.029229
209 2022-06-30  0.029803  0.029872  0.029956  0.030291  0.030985
210 2022-07-29  0.029042  0.028356  0.027134  0.026629  0.027069
211 2022-08-31  0.034615  0.034367  0.033149  0.032242  0.031975

[212 rows x 6 columns]

In [9]:
pd.read_csv('https://raw.githubusercontent.com/jianghaochu/data/master/x.csv')

HTTPError: HTTP Error 404: Not Found

In [ ]:
sys.float_info.epsilon


2.220446049250313e-16

In [ ]:
np.log(1.3268810520563034e-47)*212

-22882.997670297427

In [ ]:
A=np.random.randn(16).reshape(4,4)
np.linalg.det(A)
np.linalg.inv(A)

array([[-3.37510526,  0.18915282, -5.14545433, -0.39394699],
       [-0.09155862, -0.05190615,  0.59336073,  0.27147879],
       [-0.81353979, -0.22201297, -1.55897851,  0.08346217],
       [-1.80874827, -0.181827  , -3.00190401, -0.61620112]])

In [ ]:
A

array([[-0.1090309 , -1.9113115 ,  0.88801593, -0.65207995],
       [ 1.33410513, -1.29517203, -1.70931749, -1.65504693],
       [-0.10868698,  1.19182362, -0.7724977 ,  0.48993323],
       [ 0.45585926,  0.18636531,  1.66109196, -1.60718923]])

In [ ]:
from nelsonSiegel import NelsonSiegel
abekat=NelsonSiegel(Lambda=2.9805060433499766,sigmaS=0.05156314441167899,sigmaL=0.0005410738338867169, Xt=np.array([0.03191066026092315,0.0010436673926242554]), tauList=[2,3,5,7,10])

In [ ]:
abekat.Avector()

array([[-0.00011232, -0.00012499, -0.0001358 , -0.00014128, -0.000147  ]])

In [12]:

np.exp(np.matrix(np.zeros((2,2))))




matrix([[1., 1.],
        [1., 1.]])